<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Package $package
 */
?>
<h1><?= __('Package Document') ?></h1>
<div class="meta"><?= __('Generated by ParcelBridge') ?></div>

<h2><?= __('Package') ?></h2>
<table>
    <tr>
        <th><?= __('Tracking Number') ?></th>
        <td><?= h($package->tracking_number) ?></td>
    </tr>
    <tr>
        <th><?= __('Client Suite') ?></th>
        <td><?= $package->hasValue('client') ? h($package->client->suite_number) : '' ?></td>
    </tr>
    <tr>
        <th><?= __('Status') ?></th>
        <td><?= h($package->status?->label()) ?></td>
    </tr>
    <tr>
        <th><?= __('Weight') ?></th>
        <td><?= $this->Number->format($package->weight) ?> <?= h($package->weight_unit?->label()) ?></td>
    </tr>
    <tr>
        <th><?= __('Dimensions') ?></th>
        <td>
            <?= $this->Number->format($package->width) ?>
            x <?= $this->Number->format($package->height) ?>
            x <?= $this->Number->format($package->length) ?>
            <?= h($package->dimension_unit?->label()) ?>
        </td>
    </tr>
    <tr>
        <th><?= __('Received At') ?></th>
        <td><?= h($package->received_at) ?></td>
    </tr>
    <tr>
        <th><?= __('Shipped At') ?></th>
        <td><?= h($package->shipped_at) ?></td>
    </tr>
    <tr>
        <th><?= __('Ready for Pickup At') ?></th>
        <td><?= h($package->ready_for_pickup_at) ?></td>
    </tr>
    <tr>
        <th><?= __('Delivered At') ?></th>
        <td><?= h($package->delivered_at) ?></td>
    </tr>
</table>

<h2><?= __('Contents') ?></h2>
<div class="text-block"><?= $this->Text->autoParagraph(h($package->contents_description)) ?></div>

<?php if (!empty($package->invoice)) : ?>
    <h2><?= __('Invoice') ?></h2>
    <table>
        <tr>
            <th><?= __('Original File Name') ?></th>
            <td><?= h($package->invoice->original_filename) ?></td>
        </tr>
        <tr>
            <th><?= __('Review Status') ?></th>
            <td><?= h($package->invoice->review_status?->label()) ?></td>
        </tr>
        <tr>
            <th><?= __('Uploaded At') ?></th>
            <td><?= h($package->invoice->uploaded_at) ?></td>
        </tr>
        <tr>
            <th><?= __('Reviewed At') ?></th>
            <td><?= h($package->invoice->reviewed_at) ?></td>
        </tr>
    </table>
    <?php if (!empty($package->invoice->admin_notes)) : ?>
        <h2><?= __('Invoice Review Note') ?></h2>
        <div class="text-block"><?= $this->Text->autoParagraph(h($package->invoice->admin_notes)) ?></div>
    <?php endif; ?>
<?php endif; ?>
