<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\ShipRequest $shipRequest
 */
?>
<h1><?= __('Ship Request Manifest') ?> #<?= h($shipRequest->id) ?></h1>
<div class="meta"><?= __('Generated by ParcelBridge') ?></div>

<h2><?= __('Ship Request') ?></h2>
<table>
    <tr>
        <th><?= __('Client Suite') ?></th>
        <td><?= $shipRequest->hasValue('client') ? h($shipRequest->client->suite_number) : '' ?></td>
    </tr>
    <tr>
        <th><?= __('Status') ?></th>
        <td><?= h($shipRequest->status?->label()) ?></td>
    </tr>
    <tr>
        <th><?= __('Processing Reference') ?></th>
        <td><?= h($shipRequest->processing_reference) ?></td>
    </tr>
    <tr>
        <th><?= __('Submitted At') ?></th>
        <td><?= h($shipRequest->submitted_at) ?></td>
    </tr>
    <tr>
        <th><?= __('Processed At') ?></th>
        <td><?= h($shipRequest->processed_at) ?></td>
    </tr>
</table>

<?php if (!empty($shipRequest->notes)) : ?>
    <h2><?= __('Notes') ?></h2>
    <div class="text-block"><?= $this->Text->autoParagraph(h($shipRequest->notes)) ?></div>
<?php endif; ?>

<h2><?= __('Packages') ?></h2>
<table>
    <tr>
        <th><?= __('Tracking Number') ?></th>
        <th><?= __('Status') ?></th>
        <th><?= __('Weight') ?></th>
        <th><?= __('Contents') ?></th>
    </tr>
    <?php foreach ($shipRequest->packages_ship_requests as $join) : ?>
    <?php $package = $join->package; ?>
    <tr>
        <td><?= h($package->tracking_number) ?></td>
        <td><?= h($package->status?->label()) ?></td>
        <td><?= $this->Number->format($package->weight) ?> <?= h($package->weight_unit?->label()) ?></td>
        <td><?= h($package->contents_description) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
